### ISSUE TITLE
Avec Yves jusqu'à la mort. 

### ISSUE THREAD

**Issue by bast2109** [habsinn/journaldebord_tedua#1]
Axe de recherche :
Producteurs locaux légumes, viande, fromage, autre artisanat.
Dans le but de consommer à la sauve principalement.
Puis aider ces artisans à vendre leur production.

**Comment by habsinn** [comment]
Chouette curiosité pour les "issues". Mais pas de rapport avec le code source (de programmation informatique) du site web. Alors je ferme l' "issue" car hors sujet :)
